### ISSUE TITLE
NoMatchingViewException by Espresso using Hilt, NavigationComponent and DataBinding.

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [Neeraj1108Yadav/ModularApp#1]
I am working on Instrumentation test using Hilt, Navigation Component and Data Binding. When I execute the for test my first i.e. LoginFragment appears on the screen, but my test fail by giving me this error

**androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131296459/com.nano.modularapp:id/fragmentLogin>** 

The Complete Stacktrace

`at androidx.test.espresso.NoMatchingViewException$Builder.build(NoMatchingViewException.java:185)
                                                                                                    	at androidx.test.espresso.base.DefaultFailureHandler.lambda$getNoMatchingViewExceptionTruncater$0(DefaultFailureHandler.java:93)
                                                                                                    	at androidx.test.espresso.base.DefaultFailureHandler$$ExternalSyntheticLambda1.truncateExceptionMessage(D8$$SyntheticClass:0)
                                                                                                    	at androidx.test.espresso.base.ViewHierarchyExceptionHandler.handleSafely(ViewHierarchyExceptionHandler.java:72)
                                                                                                    	at androidx.test.espresso.base.ViewHierarchyExceptionHandler.handleSafely(ViewHierarchyExceptionHandler.java:38)
                                                                                                    	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:158)
                                                                                                    	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:120)
                                                                                                    	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:385)
                                                                                                    	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:366)
                                                                                                    	at com.nano.modularapp.FragmentLoginInstrumentedTest.test_blankField_expectedEmptyField(FragmentLoginInstrumentedTest.kt:38)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
                                                                                                    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                                                    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
                                                                                                    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                                                                                                    	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
                                                                                                    	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
                                                                                                    	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:108)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
                                                                                                    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
                                                                                                    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                                                                                                    	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                                                    	at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                                                    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                                                                                                    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                                                                                                    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                                                                                                    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                                                                                                    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                                                                                                    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                                                                                                    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                                                    	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:68)
                                                                                                    	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                                                                                                    	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:463)
                                                                                                    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2204)`

I am not able to get the solution for this one. If FragmentLogin is isDisplayed() as written in test then what view it is looking for.

StackOverFlow Question Link:
https://stackoverflow.com/questions/78803718/nomatchingviewexception-error-during-espresso-test

**Comment by Neeraj1108Yadav** [comment]
Above issue is resolved with answer mentioned in 
https://stackoverflow.com/questions/78803718/nomatchingviewexception-error-during-espresso-test
